# Generated by Django 5.2.15 on 2026-09-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ARCHIVED', 'User Archived'), ('USER_UNARCHIVED', 'User Unarchived'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PROFILE_UPDATED', 'Employee Profile Updated'), ('STUDY_BOND_SUBMITTED', 'Study Bond Submitted'), ('STUDY_BOND_HR_REVIEWED', 'Study Bond HR Reviewed'), ('STUDY_BOND_APPROVED', 'Study Bond Approved'), ('STUDY_BOND_DECLINED', 'Study Bond Declined'), ('STUDY_BOND_PAID', 'Study Bond Payment Processed'), ('STUDY_BOND_CONTINUATION_SUBMITTED', 'Study Bond Continuation Submitted'), ('STUDY_BOND_GRADE_VERIFIED', 'Study Bond Grade Verified')], max_length=50),
        ),
    ]
