# Generated by Django 5.2.15 on 2026-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=60)),
                ('to_addresses', models.TextField()),
                ('intended_to', models.TextField(blank=True, help_text='Who it would have gone to, when test mode redirected it.')),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Not sent')], default='SKIPPED', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='For Study Bond emails: the application id.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ARCHIVED', 'User Archived'), ('USER_UNARCHIVED', 'User Unarchived'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PROFILE_UPDATED', 'Employee Profile Updated'), ('STUDY_BOND_SUBMITTED', 'Study Bond Submitted'), ('STUDY_BOND_HR_REVIEWED', 'Study Bond HR Reviewed'), ('STUDY_BOND_APPROVED', 'Study Bond Approved'), ('STUDY_BOND_DECLINED', 'Study Bond Declined'), ('STUDY_BOND_PAID', 'Study Bond Payment Processed'), ('STUDY_BOND_CONTINUATION_SUBMITTED', 'Study Bond Continuation Submitted'), ('STUDY_BOND_GRADE_VERIFIED', 'Study Bond Grade Verified'), ('STUDY_BOND_RETURNED', 'Study Bond Returned to Employee'), ('STUDY_BOND_RESUBMITTED', 'Study Bond Resubmitted'), ('STUDY_BOND_WITHDRAWN', 'Study Bond Withdrawn'), ('STUDY_BOND_APPROVER_CHANGED', 'Study Bond Approver Changed'), ('STUDY_BOND_LINK_SENT', 'Study Bond Approval Link Sent')], max_length=50),
        ),
    ]
