# Generated by Django 5.2.15 on 2026-07-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationletter',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary in BWP', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='employee_id_number',
            field=models.CharField(blank=True, help_text="Employee's national ID or staff ID number", max_length=50),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='job_title',
            field=models.CharField(default='Not specified', help_text='e.g. Research Assistant, Finance Officer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='plot_number',
            field=models.CharField(blank=True, help_text='e.g. 1234', max_length=100),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='po_box',
            field=models.CharField(blank=True, help_text='e.g. PO Box 1234', max_length=100),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='postal_city',
            field=models.CharField(blank=True, default='Gaborone', max_length=100),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], default='Ms.', max_length=10),
        ),
        migrations.AddField(
            model_name='confirmationletter',
            name='ward',
            field=models.CharField(blank=True, help_text='e.g. Tlokweng', max_length=100),
        ),
        migrations.AlterField(
            model_name='confirmationletter',
            name='purpose',
            field=models.CharField(blank=True, help_text='e.g. Bank confirmation, Visa application', max_length=200),
        ),
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name as it appears on letters e.g. Lindiwe Maidi', max_length=200)),
                ('job_title', models.CharField(default='Human Resources Coordinator', max_length=200)),
                ('organisation', models.CharField(default='Botswana-UPenn Partnership', max_length=200)),
                ('telephone', models.CharField(blank=True, help_text='e.g. 3554855', max_length=50)),
                ('signature_image', models.ImageField(blank=True, help_text='Upload a scanned signature image (PNG with transparent background recommended)', null=True, upload_to='hr_signatures/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one HR profile should be active at a time')),
                ('hr_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HR Profile',
                'verbose_name_plural': 'HR Profiles',
            },
        ),
    ]
