# Generated by Django 5.2.15 on 2026-07-29 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_confirmationletter_annual_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=10)),
                ('employee_id_number', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(max_length=200)),
                ('plot_number', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('po_box', models.CharField(blank=True, max_length=100)),
                ('postal_city', models.CharField(blank=True, default='Gaborone', max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Review'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_requests_actioned', to=settings.AUTH_USER_MODEL)),
                ('confirmation_letter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_request', to='hr.confirmationletter')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
