# Generated by Django 5.2.15 on 2026-08-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_letterrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBondRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type', models.CharField(choices=[('OPERATIONS', 'Operations'), ('RESEARCH', 'Research / Studies')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('program_title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subject_costs', models.DecimalField(decimal_places=2, help_text='Cost of subjects, limit 3 per semester', max_digits=12)),
                ('amount_paid_by_bup', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='study_bond_receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval to Register'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('REGISTERED', 'Approved to Register'), ('DECLINED', 'Declined'), ('COMPLETED', 'Completed – Grade Verified')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approver_name', models.CharField(blank=True, max_length=200)),
                ('approver_job_title', models.CharField(blank=True, max_length=200)),
                ('approver_signature', models.ImageField(blank=True, null=True, upload_to='study_bond_signatures/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('hr_verified_salary', models.DecimalField(blank=True, decimal_places=2, help_text="Employee's verified annual base pay", max_digits=12, null=True)),
                ('hr_cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Confirmed cap: 10% of base pay or BWP 3000/yr equivalent, whichever is less', max_digits=12, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('grade_received', models.CharField(blank=True, max_length=50)),
                ('verifier_name', models.CharField(blank=True, max_length=200)),
                ('verifier_job_title', models.CharField(blank=True, max_length=200)),
                ('verifier_signature', models.ImageField(blank=True, null=True, upload_to='study_bond_signatures/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bonds_registered', to=settings.AUTH_USER_MODEL)),
                ('assigned_pi', models.ForeignKey(blank=True, limit_choices_to={'role': 'PI'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bonds_as_pi', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bonds_hr_reviewed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_bond_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bonds_grade_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
