# Generated by Django 5.2.15 on 2026-08-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(default='Director', max_length=200)),
                ('organisation', models.CharField(default='Botswana-UPenn Partnership', max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('signature_image', models.ImageField(blank=True, help_text='Upload a scanned signature image (PNG with transparent background recommended)', null=True, upload_to='director_signatures/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one Director profile should be active at a time')),
                ('director_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Director Profile',
                'verbose_name_plural': 'Director Profiles',
            },
        ),
    ]
