# Generated by Django 5.2.15 on 2026-10-05 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. Dr, Prof', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('approval_email', models.EmailField(help_text='The address approval links are sent to.', max_length=254)),
                ('uses_link', models.BooleanField(default=True, help_text='Tick if this PI approves by emailed link. Untick for a PI who signs in with a BUP account.')),
                ('email_checked_at', models.DateTimeField(blank=True, null=True)),
                ('email_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_emails_checked', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PI Profile',
                'verbose_name_plural': 'PI Profiles',
            },
        ),
    ]
