# Generated by Django 5.2.15 on 2026-09-05 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyBondApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('FRESH', 'Fresh Application'), ('CONTINUATION', 'Continuation')], max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING_PAYMENT', 'Pending Payment'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('program_title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_acknowledged', models.BooleanField(default=False, help_text='Employee confirms agreement to be bound by the BUP Education Policy.')),
                ('verified_base_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_of_subjects', models.DecimalField(blank=True, decimal_places=2, help_text='Limit 3 subjects per semester — enforced procedurally by HR, not by this field.', max_digits=12, null=True)),
                ('amount_paid_by_bup', models.DecimalField(blank=True, decimal_places=2, help_text='Must not exceed min(verified_base_pay × 10%, BWP 3000) per fiscal year.', max_digits=12, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('program_relevant', models.BooleanField(blank=True, null=True)),
                ('accredited_institution', models.BooleanField(blank=True, null=True)),
                ('good_standing_6_months', models.BooleanField(blank=True, null=True)),
                ('tuition_cap_balance_ok', models.BooleanField(blank=True, null=True)),
                ('supervisor_notified', models.BooleanField(blank=True, help_text='Only relevant if the employee is requesting leave to attend classes.', null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('approver_comment', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='study_bond_receipts/')),
                ('finance_processed_at', models.DateTimeField(blank=True, null=True)),
                ('grade_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('grade_verified_at', models.DateTimeField(blank=True, null=True)),
                ('grade_notes', models.TextField(blank=True)),
                ('approver', models.ForeignKey(help_text="linked_project.pi, unless the applicant IS that PI, or there's no linked_project — then the Director.", on_delete=django.db.models.deletion.PROTECT, related_name='study_bond_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_bond_applications', to=settings.AUTH_USER_MODEL)),
                ('finance_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bond_payments_processed', to=settings.AUTH_USER_MODEL)),
                ('grade_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bond_grade_verifications', to=settings.AUTH_USER_MODEL)),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bond_hr_reviews', to=settings.AUTH_USER_MODEL)),
                ('linked_project', models.ForeignKey(blank=True, help_text='Which BUP research project the employee is on, used only to determine the approver. This is NOT the external academic program being sponsored — see program_title/institution below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bond_applications', to='research.study')),
                ('previous_application', models.ForeignKey(blank=True, help_text='Required for a continuation. Fresh applications leave this blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuations', to='employee_services.studybondapplication')),
            ],
            options={
                'verbose_name': 'Study Bond Application',
                'verbose_name_plural': 'Study Bond Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyBondAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('ADMISSION_LETTER', 'Admission Letter'), ('COURSE_CONTENT', 'Course Content'), ('QUOTATION', 'Course Quotation'), ('ACCREDITATION', 'Accreditation'), ('RESULTS', 'Results'), ('PREVIOUS_RECEIPT', 'Previous Receipt')], max_length=30)),
                ('file', models.FileField(upload_to='study_bond_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='employee_services.studybondapplication')),
            ],
            options={
                'ordering': ['attachment_type'],
            },
        ),
    ]
