# Generated by Django 5.2.15 on 2026-10-05 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studybondapplication',
            name='approved_by_link',
            field=models.BooleanField(default=False, help_text='True when the approver decided through the emailed one-time link instead of signing in.'),
        ),
        migrations.AddField(
            model_name='studybondapplication',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='1 = first submission. Goes up each time HR returns it and the employee resubmits.'),
        ),
        migrations.AddField(
            model_name='studybondapplication',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studybondapplication',
            name='withdrawn_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studybondattachment',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='Set when the employee uploads a newer file of the same type. The old file is kept, not deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='studybondapplication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING_PAYMENT', 'Pending Payment'), ('COMPLETED', 'Completed'), ('RETURNED', 'Returned for Changes'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('sent_to', models.CharField(help_text='The address the link was emailed to.', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_tokens', to='employee_services.studybondapplication')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyBondReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text="HR's note to the employee. It is emailed to them as written.")),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='employee_services.studybondapplication')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_bond_returns_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['returned_at'],
            },
        ),
    ]
