# Generated by Django 5.2.15 on 2026-10-08 03:45

import django.db.models.deletion
import django.utils.timezone
import onboarding.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetailsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('position_title', models.CharField(blank=True, max_length=200)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('assumption_date', models.DateField(blank=True, help_text='Date of assumption of duty', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SENT', 'Waiting for the new employee'), ('SUBMITTED', 'Submitted to HR'), ('CLOSED', 'Closed')], default='SENT', max_length=12)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reopen_note', models.TextField(blank=True)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('full_names', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('PREFER_NOT', 'Prefer not to say')], max_length=12)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('OTHER', 'Other')], max_length=12)),
                ('id_number', models.CharField(blank=True, help_text='ID (Omang) or passport number', max_length=40)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('postal_address', models.TextField(blank=True)),
                ('physical_address', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('kin_name', models.CharField(blank=True, max_length=200)),
                ('kin_relationship', models.CharField(blank=True, max_length=100)),
                ('kin_telephone', models.CharField(blank=True, max_length=30)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_telephone', models.CharField(blank=True, max_length=30)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('qualifications', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch_code', models.CharField(blank=True, max_length=20)),
                ('bank_branch_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('declaration_name', models.CharField(blank=True, max_length=200)),
                ('declaration_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_details_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalDetailsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ID_COPY', 'Copy of Passport / Omang'), ('HEALTH_CERT', 'Copy of Health Professional Certificate'), ('EXEMPTION_CERT', 'Copy of exemption certificate'), ('QUALIFICATIONS', 'Certified copies of qualifications')], max_length=20)),
                ('file', models.FileField(storage=onboarding.models.get_private_storage, upload_to=onboarding.models.upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.personaldetailsrequest')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
    ]
